version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather
  
  generate_summary:
    run: python:latest python analysis/summary.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table1: output/summary1.csv
        table2: output/summary2.csv
        table3: output/summary3.csv
